version: "2.1"

services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - '${DOCKER_VOLUME_STORAGE:-/home/op/persist}/transmission/config:/config'
      - '${DOCKER_VOLUME_STORAGE:-/home/op/persist}/transmission/downloads:/downloads'
      - '${DOCKER_VOLUME_STORAGE:-/home/op/persist}/transmission/watch:/watch'
    ports:
      - 9091:9091 # web ui
      - 51413:51413 # torrent port tcp
      - 51413:51413/udp # torrent port udp
    restart: unless-stopped
