version: "2.1"

services:
  sonarr:
    image: cr.hotio.dev/hotio/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - ${DOCKER_VOLUME_STORAGE:-/home/op/persist}/sonarr/config:/config
      - ${DOCKER_VOLUME_STORAGE:-/home/op/persist}/sonarr/tv:/data/tv
      - ${DOCKER_VOLUME_STORAGE:-/home/op/persist}/sonarr/downloads:/downloads # Should be the same as the download client's folder
    ports:
      - 8989:8989
    restart: unless-stopped
