version: "3.7"
services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    environment:
      - TZ=America/New_York
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${DOCKER_VOLUME_STORAGE:-/home/op/persist}/caddy/CaddyFile:/etc/caddy/Caddyfile
      - ${DOCKER_VOLUME_STORAGE:-/home/op/persist}/caddy/data:/data
      - ${DOCKER_VOLUME_STORAGE:-/home/op/persist}/caddy/config:/config
