version: '2'

services:
  droppy:
    container_name: droppy
    image: silverwind/droppy
    ports:
      - 8989:8989
    volumes:
      - ${DOCKER_VOLUME_STORAGE:-/home/op/persist}/droppy/config:/config
      - /path/to/my/data/for/sharing:/files # path to shared files
    environment:
      - UID=1000
      - GID=1000
      - TZ="America/New_York"
    restart: unless-stopped
