version: "3"

services:
  pwndrop:
    container_name: pwndrop
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/New_York
      - SECRET_PATH=pwndrop # secret path your admin mgmt interface will be
    image: linuxserver/pwndrop:latest
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_VOLUME_STORAGE:-/home/op/persist}/pwndrop/config:/config
