version: "3"

services:
  papermerge:
    container_name: papermerge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    hostname: papermerge
    image: linuxserver/papermerge:latest
    restart: unless-stopped
    volumes:
      - ${DOCKER_VOLUME_STORAGE:-/home/op/persist}/papermerge/importer_dir:/mnt/media/importer_dir
      - ${DOCKER_VOLUME_STORAGE:-/home/op/persist}/papermerge/config:/config
      - ${DOCKER_VOLUME_STORAGE:-/home/op/persist}/papermerge/data:/data
