version: "3"

services:
  deemix:
    container_name: deemix
    environment:
      - PUID=1000
      - PGID=1000
    hostname: deemix
    image: registry.gitlab.com/bockiii/deemix-docker:latest
    restart: unless-stopped
    volumes:
      - ${DOCKER_VOLUME_STORAGE:-/home/op/persist}/deemix/config:/config
      - ${DOCKER_VOLUME_STORAGE:-/home/op/persist}/deemix/downloads:/downloads
