version: "3.9"
services:
  coder:
    # This MUST be stable for our documentation and
    # other automations.
    image: ghcr.io/coder/coder:${CODER_VERSION:-latest}
    env_file: docker-compose.env

    # If the coder user does not have write permissions on
    # the docker socket, you can uncomment the following
    # lines and set the group ID to one that has write
    # permissions on the docker socket.
    group_add:
      - "62" # docker group on host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      coderdb:
        condition: service_healthy
  coderdb:
    image: "postgres:14.2"
    env_file: docker-compose.env
    volumes:
      - ${DOCKER_VOLUME_STORAGE:-/home/op/persist}/coder/data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U coder -d coder",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
networks:
  default:
    external: true
    name: npm_proxy