version: "2.1"

services:
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - AUTO_UPDATE=true #optional
    volumes:
      - ${DOCKER_VOLUME_STORAGE:-/home/op/persist}/jackett/config:/config
      - ${DOCKER_VOLUME_STORAGE:-/home/op/persist}/jackett/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
