version: '3.3'

services:
    flaresolverr:
        image: ghcr.io/flaresolverr/flaresolverr:latest
        container_name: flaresolverr
        ports:
            - 8191:8191
        environment:
            - LOG_LEVEL=info
            - TZ=America/New_York
        restart: unless-stopped
