version: "3"

services:
  npm:
    container_name: npm
    environment:
      - TZ=America/New_York
    hostname: npm
    user: 0:1000
    image: jc21/nginx-proxy-manager:latest
    ports:
      - 443:443/tcp # HTTPS
      - 81:81/tcp # MGMT UI
      - 80:80/tcp # HTTP
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/bin/check-health"]
      interval: 30s
      timeout: 3s
    volumes:
      - ${DOCKER_VOLUME_STORAGE:-/home/op/persist}/nginx-proxy-manager/data:/data
      - ${DOCKER_VOLUME_STORAGE:-/home/op/persist}/nginx-proxy-manager/letsencrypt:/etc/letsencrypt

networks:
  default:
    external: true
    name: npm_proxy