version: '3.4'
services:
  bibliogram:
    image: schklom/bibliogram
    container_name: bibliogram
    volumes:
      - ${DOCKER_VOLUME_STORAGE:-/home/op/persist}/bibliogram/config.js:/app/config.js:ro
    ports:
      - '10407:10407'
    restart: unless-stopped