version: '3'
services:
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    environment:
      - PASSWORD=MySecureLoginPassword
      - TZ="America/New_York"
    volumes:
      - ${DOCKER_VOLUME_STORAGE:-/home/op/persist}/homarr/configs:/app/data/configs
      #- ${DOCKER_VOLUME_STORAGE:-/home/op/persist}/homarr/icons:/app/public/icons # optional for custom icons
    ports:
      - '7575:7575'
