version: "3"

services:
  wikijs:
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    image: linuxserver/wikijs:latest
    container_name: wikijs
    restart: unless-stopped
    ports:
      - 3000:3000 # WEB UI
    volumes:
      - ${DOCKER_VOLUME_STORAGE:-/home/op/persist}/wikijs/config:/config
      - ${DOCKER_VOLUME_STORAGE:-/home/op/persist}/wikijs/data:/data
    links:
      - db
      
  db:
    environment:
      - POSTGRES_PASSWORD=MySecureDatabasePassword
      - POSTGRES_USER=wikijs
      - POSTGRES_DB=wikijs
    container_name: postgresql
    image: postgres:13.4-bullseye
    restart: unless-stopped
    volumes:
      - ${DOCKER_VOLUME_STORAGE:-/home/op/persist}/wikijs/database:/var/lib/postgresql/data
