version: "3"

services:
  fail2ban:
    container_name: fail2ban
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - TZ=America/New_York
      - F2B_DB_PURGE_AGE=14d
    image: crazymax/fail2ban:latest
    network_mode: host
    restart: unless-stopped
    volumes:
      - ${DOCKER_VOLUME_STORAGE:-/home/op/persist}/fail2Ban/data:/data
      - /path/to/my/logs/to/monitor:/var/log
      #- ${DOCKER_VOLUME_STORAGE:-/home/op/persist}/traefik/logs:/var/log/traefik
