version: "3"
services:
  answer:
    container_name: answer
    image: answerdev/answer
    ports:
      - '9080:80'
    restart: unless-stopped
    volumes:
      - ${DOCKER_VOLUME_STORAGE:-/home/op/persist}/answer/data:/data
